name: Clippy

on:
  push:
    branches:
    - master
    - travis

  pull_request:
    branches:
    - master

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Clippy
      run: cargo clippy
